export const INIT_CARD_DATA = 'INIT_CARD_DATA';

export const SAVE_EDITED_CARD_DATA = 'SAVE_EDITED_CARD_DATA';

export const DELETE_CARD_DATA = 'DELETE_CARD_DATA';

export const LIKE_TOGGLE = 'LIKE_TOGGLE';
