export const SHOW_MODAL = 'SHOW_MODAL';

export const CLOSE_ALL_MODALS = 'CLOSE_ALL_MODALS';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';

export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const TOGGLE_LOADER = 'TOGGLE_LOADER';

export const CHANGE_NAVIGATION = 'CHANGE_NAVIGATION';

export const CHANGE_CARDS_LAYOUT_VIEW = 'CHANGE_CARDS_LAYOUT_VIEW';
